### ISSUE TITLE
preset molto diversi da prima...

### ISSUE THREAD

**Issue by skysix2** [kokoko3k/koko-aio-slang#13]
ciao !

finora ho usato il preset monitor-FXAA-aperturegrille con degli aggiustamenti e varianti che ho salvato individualmente
ero alla versione 1.9.1 (ma anche nelle versioni precedenti , tutto ok)
prima di passare a batocera 41 aggiorno a 1.9.50 e riprovo tutti i miei preset, ma è tutto diverso , diciamo che lo shader risulta molto più finto, piu LCD style ( appena posso ti aggiungo degli screenshot di confronto, prima e dopo )

dati tutti i nuovi sviluppi , è possibile impostarlo in modo da avere un risultato similare a prima?
oppure mi consigli di rimanere alla versione precedente e bon?

grazie!!

**Comment by kokoko3k** [comment]
I preset di default sono rimasti pressochè identici; tuttavia ci sono state modifiche al codice dello shader, che l'hanno reso migliore e più leggero, alcuni parametri sono cambiati per esempio, e addirittura alcune passate rimosse; quest'ultima modifica, soprattutto, rende i preset salvati in modo "full" e non come "simple preset" incompatibili con il nuovo shader.

Ti assicuro che lo shader non ha perso alcuna funzionalità, per cui per rispondere alla tua domanda: sì,  è possibile ottenere gli stessi risultati precedenti, ma occorre partire dai preset base e rifare i tweak personali insomma.

Il consiglio è di salvare i preset sempre come "simple presets", perchè hanno maggior probabilità di mantenere compatibilità con le versioni a venire.

**Comment by skysix2** [comment]
ok ! 
io uso i "simple preset" e li cambio al volo tramite hotkey di RA, comunque stasera ti posto i preset e gli screnshot così puoi capirmi meglio 
grazie intanto !!

**Comment by kokoko3k** [comment]
In alcune condizioni retroarch salva preset come full anche se è impostato a simple, per cui controllali anche con un editor di testo...

**Comment by skysix2** [comment]
rieccoci!!

piccolo spiegone: 
- al boot di batocera rinomino in .OLD la path originale /usr/share/batocera/shaders/bezel/koko-aio 
- aggiungo la cartella koko-aio nella versione voluta, prima 1.9.1 adesso 1.9.50
- aggiungo i miei "simple preset" in /usr/share/batocera/shaders/

ecco il mio simple preset con il quale ho fatto i due screenshots:

`#reference "bezel/koko-aio/Presets-ng/Monitor-FXAA_sharp-aperturegrille.slangp"

DO_AMBILIGHT = "0.0"
DO_SPOT = "0.000000"
DO_GLOBAL_SHZO = "1.000000"
GLOBAL_ZOOM = "0.900000"
SATURATION = "0.95"
DO_RF_NOISE = "1.0"
RF_NOISE_STRENGTH = "0.04" # nella 1.9.50 dovrebbe essere "uniform qualcosa"
DO_SAT_BLEED = "1.0"
SAT_BLEED_PAL = "1.0"`

questo lo screen bello in versione 1.9.1:

![xmcota-241105-205537---1 9 1](https://github.com/user-attachments/assets/72d70a92-bbf3-484e-98be-e6b91242ad75)

questo lo screen brutto in versione 1.9.50:

![xmcota-241105-205259---1 9 50](https://github.com/user-attachments/assets/f27f93b5-9cb3-4fd6-b21e-4677f208a3d5)

zoomma negli angoli per controllare il logo marvel in rosso . e le scritte in giallo ad esempio la versione o i testi in basso...
nella versione 1.9.50 sembrano colori a pastello , gli steli delle lettere sono perfettamente dritti e le estremità perfettamente tonde, anche le riflessioni sulla cornice quasi inesistenti

nella vecchia versione 1.9.1 i pixel sono piu stondati e le scritte come anche il logo sono molto piu CRT way

**Comment by skysix2** [comment]
> In alcune condizioni retroarch salva preset come full anche se è impostato a simple, per cui controllali anche con un editor di testo...

ok, ma non li ho salvati da retroarch , ho scritto a mano i file dopo aver guardato come si scrivono i riferimenti su un'altro "simple preset" già esistente

**Comment by kokoko3k** [comment]
Hai ragione,
il preset con fxaa è stato modificato nell'intento di miglirare la resa secondo lo scopo che avrebbe, ossia quello di definire i bordi delle forme, perchè non è mai stato inteso come un preset che doveva ricreare un effetto crt, ma per l'appunto proprio per avere un look "più finto" come scrivi tu.

Le riflessioni invece sono cambiate un pò in tutti i preset per renderle più realistiche, forse ho un pò esagerato?

Altra cosa che mancava nella versione di batocera, e che ha modificato in tutti i preset, è la presenza del warpedglow. Esso ingrandisce le aree chiare rispetto a quelle scure nelle zone ad alto contrasto, e quello secondo me è un effetto presente nei crt, che tra l'altro serve anche a ridurre l'antialias.

Inoltre Il rumore RF è stato spostato dopo il glow in modo da avere apparire più definito (settaggio:1); per avere il comportamento precedente settalo a -1:

Comunque, per avere un look come il prima, prova questi override:

```
Bezel:
reflection strength -> 0.35
diffusion strength -> 0.15
light fadeout distance: 0.9
less reflections in the corners: 0.5
reflection sharpness: 0.0

glow/blur:
Sharp X -0.8
shatp y  s7.0
warped glow x, y: 0.0


RF Noise: -1
Uniform noise 0.17
snow noise: 0.0
```

![Screenshot_20241106_082342](https://github.com/user-attachments/assets/ce27ba14-69dc-4cb0-aa65-201af38d4609)

C'è ancora una piccola differenza negli spigoli, perchè FXAA adesso evita di arrorondarli oltremodo; questo in effetti non me l'aspettavo, ma credo sia tutto sommato un miglioramento.

**Comment by skysix2** [comment]
ok , provo appena possibile, grazie intanto

> Altra cosa che mancava nella versione di batocera, e che ha modificato in tutti i preset, è la presenza del warpedglow. Esso ingrandisce le aree chiare rispetto a quelle scure nelle zone ad alto contrasto, e quello secondo me è un effetto presente nei crt, che tra l'altro serve anche a ridurre l'antialias.

pero io uso sempre lo shader scaricato in zip da questo github , non uso mai quello già presente in batocera o quello pachettizzato che si trova nei download

anche la modifica negli spigoli/angoli si , mi sono dimenticato di menzionarla , quindi non è un fattore di zoom ok

un'altra cosa , ho anche un preset dove disabilito tutto tranne la curvatura dello schermo e la cornice riflettente, praticamente stock ma incapsulato nel CRT:
nella versione 1.9.1 tutto OK
nella versione 1.9.50 OK ma con il gamma molto basso o con la luminosità a manetta, dopo varie prove nella parte del color_correction non sono riuscito a risolvere (se riesco nel primo pomeriggio ti posto il preset)

**Comment by skysix2** [comment]
si il warpedglow è carino, quindi nella versione 1.9.50 è già abilitato ?

ho visto che hai anche aggiunto altri preset "aperturegrille" , ma presumo che non serva provare quelli in quanto mi allontanerebbero di più dal risultato giusto?

**Comment by kokoko3k** [comment]
> pero io uso sempre lo shader scaricato in zip da questo github , non uso mai quello già presente in batocera o quello pachettizzato che si trova nei download

...non ricordo esattamente quando è stato aggiunto warpedglow, ma non mi sembrava attivo nell'immagine che hai postato.

> anche la modifica negli spigoli/angoli si , mi sono dimenticato di menzionarla , quindi non è un fattore di zoom ok

...non ho capito cosa intendi qui su, se è per la minore riflessione negli angoli del bezel, l'algoritmo è stato migliorato, adesso la transizione è più soft di prima, e non si può avere come prima, ma puoi ancora modificare la forza dell'effetto, come ti ho indicato nei parametri da modificare.

> nella versione 1.9.50 OK ma con il gamma molto basso o con la luminosità a manetta, dopo varie prove nella parte del color_correction non sono riuscito a risolvere (se riesco nel primo pomeriggio ti posto il preset)

Se ho capito bene, forse il problema risiede nel fatto che adesso la gamma in ingresso e quella di uscita sono applicate sempre, indipendentemente dal fatto che tu abiliti o meno la correzione dei colori.
la regola che lega gamma in e gamma out è che gamma out dev'essere uguale a 1/gamma_in
Per cui o imposti entrambi a 1.0, oppure imposti gamma in a 2.2 e gamma out a 0.45.
gamma out può in verità essere abbassato quando l'immagine risulta troppo scura per compensare scanline, maschere etc.

**Comment by skysix2** [comment]
ok ecco il preset "stock nel CRT", per riferimento

`#reference "bezel/koko-aio/Presets-ng/Monitor-FXAA_sharp-aperturegrille.slangp"

DO_AMBILIGHT = "0.0"
DO_BEZEL = "1.0"
DO_BLOOM = "0.0"
DO_CCORRECTION = "0.0"
DO_CURVATURE = "1.0"
DO_DYNZOOM = "0.0"
DO_FXAA = "0.0"
DO_HALO = "0.0"
DO_IN_GLOW = "0.0"
DO_NTSC_ARTIFACTS = "0.0"
DO_PIXELGRID = "0.0"
DO_SPOT = "0.0"
DO_RF_NOISE = "0.0"
DO_SAT_BLEED = "0.0"
SAT_SHIFT_RGB = "0.0"
DO_VIGNETTE = "0.0"`

stasera riesco a fare le prove...

**Comment by skysix2** [comment]
di nuovo un ultima domanda,
nel pacchetto scaricabile dai download in batocera : koko-aio 1.9 immersive duimon bezel
è possibile ridurre l'effetto della divisione tra i pixel ? (credo sia la griglia dei pixel o scanlines)
andando a modificare direttamente lo shader , perchè da RA non si può come sai...

**Comment by kokoko3k** [comment]
devi trovare il settaggio corrispondente in user-config.txt e modificarlo da lì, non so quale sia nello specifico.

**Comment by skysix2** [comment]
ok tenterò, 

grazie del tuo lavoro e del tuo tempo !!

**Comment by skysix2** [comment]
eccoci !! 
tutto bene ! 
tranne una cosa, 
- rf_noise in versione 1.9.1 agiva piu sulle parti chiare dell'immagine, con un effetto di "vibrazione" molto bello
- rf_noise in versione 1.9.50 invece agisce sulle parti scure dell'immagine e l'effetto "vibrazione" sparisce

ce un settaggio per imitare la vecchia versione ?

**Comment by kokoko3k** [comment]
RF_NOISE_SPARK é una dimenticanza.

Per avere rf noise vecchio, dovrebbe bastare settalo a -1 e disabilitare snow noise.

**Comment by skysix2** [comment]
si ho provato -1 e anche 1 , snow noise è impostato a 0.0 come da tue indicazioni
ma l'effetto finale non cambia, in pratica è in negativo rispetto al vecchio...

**Comment by kokoko3k** [comment]
Mi spiace, ma non riesco a immaginare cosa possa essere, non mi pare ci fossero condizioni che applicavano il rumore in base alla luminositá.

Puoi aprire una immagine di un gradiente da nero a bianco in retroarch e mostrarmi come agisce diversamente il rumore tra prima e dopo?

**Comment by skysix2** [comment]
vedo di riuscire...
come al solito , questa sera ...

**Comment by kokoko3k** [comment]
Credo d'aver capito che intendi.
Il rumore veniva prima applicato prima del CVBS sat bleed, quindi ne influenzava la resa.
Adesso viene applicato dopo, quindi non lo fa.

Cerco di trovare un modo per risolvere.

**Comment by skysix2** [comment]
ok ! 
grazie , provo appena posso ...

nel frattempo sono riuscito a fare delle registrazioni:
sono mp4 zippati , registrati con OBS, quindi estrai e vai di vlc

versione 1.9.1 si vede bene il tremolio nelle parti chiare
[koko-1.9.1--2024-11-07_23-42-30.zip](https://github.com/user-attachments/files/17670337/koko-1.9.1--2024-11-07_23-42-30.zip)

versione 1.9.50 si vede male , nel senso che non si vede il rumore ne sul chiaro ne sul scuro
[koko-1.9.50--2024-11-07_23-44-57.zip](https://github.com/user-attachments/files/17670350/koko-1.9.50--2024-11-07_23-44-57.zip)

ma ti assicuro che su batocera v40 con la solita rom , RA in versione 1.18, koko-1.9.50  il rumore si vede bene solo nelle zone scure

**Comment by kokoko3k** [comment]
Ho guardato i video.
Ciò che noto non è una differenza nell'applicazione del rumore sui chiari o sugli scuri, ma una differente forza generale del rumore.

Ciò è dovuto al fatto che il parametro adesso è intenzionalmente moltiplicato per sè stesso prima d'essere applicato; questa modifica permette di spostare la precisione del parametro sui valori bassi..

Come vedi, sui bassi livelli, aumentando 0.3 di 0.05, l'incremento effettivo è di 0.032
RF_NOISE_STRENGTH = 0.3 -> applica 0.3*0.3 = 0.09
RF_NOISE_STRENGTH = 0.35 -> applica 0.35*0.35 = 0.122

...mentre quando vi si avvicina agli alti valori, hai l'effetto inverso (parametro aumenta di 0.5, effetto aumenta di 10).
RF_NOISE_STRENGTH = 0.95 -> applica 0.95*0.95=0.90
RF_NOISE_STRENGTH = 1.0 -> applica 1*1 = 1

Insomma, aumenta il parametro.

**Comment by skysix2** [comment]
eccoci !
hai guardato i video in fullhd?

ho provato la tua ultima versione e non noto differenze rispetto a prima , con la ROM , non ho ancora provato con il gradiente
e forse dovevo rimettere il parametro RF_NOISE a 1.0 e non a -1.0 o sbaglio ?

proverò anche i nuovi parametri di RF_NOISE_STRENGTH , per farlo uguale a prima (0.04) dovei impostarlo quindi a 0.2

**Comment by skysix2** [comment]
ok ! 
grazie mille!!! 
come al solito riesco a provare stasera ...

**Comment by kokoko3k** [comment]
Ok, ti invito a provare l'ultimissima, dato che ho fatto altre modifiche e qui sembra identica alla precedente.

**Comment by skysix2** [comment]
eccoci !
scusa il ritardo , ho provato quest'ultima versione ed è tutto OK
grazie ancora !!!
