### ISSUE TITLE
Backport to GLSL for wider support for emulators (including 86box) and offer prebuilt binaries

### ISSUE THREAD

**Issue by TheSystemGuy1337** [kokoko3k/koko-aio-slang#14]
I think this is easy to explain. What you have is a great CRT shader. But I would definitely like to see GLSL ports and precompiled versions of the shader so it's more accessible. 86box would benefit from this shader, but 86box only supports GLSL shaders.

**Comment by kokoko3k** [comment]
Hi there,
koko-aio started as a glsl shader for FS-UAE, but moved to slang(p) afterwards because the latter allowed for more advanced stuff which wasn't possible otherwise.

So I'm afraid I've to give a negative answer.

You can still emulate x86 on Retroarch, right?

**Comment by TheSystemGuy1337** [comment]
> Hi there, koko-aio started as a glsl shader for FS-UAE, but moved to slang(p) afterwards because the latter allowed for more advanced stuff which wasn't possible otherwise.
> 
> So I'm afraid I've to give a negative answer.
> 
> You can still emulate x86 on Retroarch, right?

I don't think so. There's DOSBOX, but that isn't remotely like 86box. I'll see if I can raise a question about adding SLANGP shader support in 86box

**Comment by kokoko3k** [comment]
Check librashader too.

**Comment by TheSystemGuy1337** [comment]
Added that as well. Sorry if I possibly wasted your time.

**Comment by kokoko3k** [comment]
Hey, no worries!

**Comment by TheSystemGuy1337** [comment]
> Hey, no worries!

I think you are entitled to some compensation for your time. Please take this.

https://www.youtube.com/watch?v=THc1X-kEX4E
