### ISSUE TITLE
Latest GitHub - Vignette Enable Affects Background

### ISSUE THREAD

**Issue by estefan3112** [kokoko3k/koko-aio-slang#3]
EDIT: Only occurs in vertical games, not horizontal games. Both FinalBurn Neo and MAME2003.

Hi, I just pulled the changes of last week, and Vignette Enable causes this effect:

<img width="1440" alt="Bildschirm­foto 2023-02-10 um 22 06 20" src="https://user-images.githubusercontent.com/24915559/218197612-d9f5842b-3014-433d-9beb-9b86faf90c4c.png">

Configuration:

#reference "../../shaders/shaders_slang/bezel/koko-aio/monitor-slotmask-bloom-bezel.slangp"
LUMINANCE = "0.000000"
BEZEL_R = "-0.220000"
BEZEL_G = "-0.220000"
BEZEL_B = "-0.220000"
BEZEL_INNER_ZOOM = "-0.110000"
BEZEL_FRAME_ZOOM = "0.090000"
DO_BG_IMAGE = "1.000000"
BG_IMAGE_OFFX = "0.000500"
BG_IMAGE_OFFY = "0.009500"
BG_IMAGE_ZOOM = "0.999500"
BG_IMAGE_ROTATION = "1.000000"
DO_AMBILIGHT = "0.000000"
bg_under = "../../shaders/shaders_slang/bezel/koko-aio/textures/arcade_textures/1942.png"

**Comment by kokoko3k** [comment]
Wops!
I know what i changed, so rolling back is definitely possible, but I've to understand why it actually happens and i'll do by the start of the next week.

Thank you for spotting the bug!

**Comment by estefan3112** [comment]
My previous branch merge was 1 February, so the change must have been thereafter.

**Comment by kokoko3k** [comment]
Sorry, pal, this is going to be harder than expected, because it works fine here:
![image](https://user-images.githubusercontent.com/1230726/218252431-4895511d-8e4f-417a-8862-d6c665360bac.png)

Could you try to bisect the issue by identifying the exact commit that broke it for you?

**Comment by estefan3112** [comment]
Bingo - I downloaded: 6667407933b1cc20f09f07312eae6d5dab971f43 - the problem arises.
Then I downloaded one commit earlier: 8bcaf436d08f80bbd938529216ae35ff73aadb49 - still works
Curious now whether there comes something in the logfiles (probably not).

**Comment by estefan3112** [comment]
Just infos in the logfiles. To be on the safe side, I also checked your stock slotmask shader with stock background.

Easy workaround for the time being: turning off vignette.

<img width="1440" alt="Bildschirm­foto 2023-02-11 um 16 11 25" src="https://user-images.githubusercontent.com/24915559/218266412-83a30e40-40fe-402d-a297-02b5ae5783ce.png">

**Comment by kokoko3k** [comment]
still weird i cannot reproduce...
I think i'll make a branch to debug this issue, but i'd have to ask you to do tests on it on my blind commits there to try to understand what causes the issue.
Meanwhile, is there something out of ordinary on your setup?

**Comment by kokoko3k** [comment]
Also, what puzzles me is that it "cuts" even your bezel corners.
Does the issue happen to you only when enabling background images?

**Comment by estefan3112** [comment]
To narrow down things, I'll do tests tomorrow under Windows and iOS with the latest Github

**Comment by kokoko3k** [comment]
Sorry to hear that.
From a code point of view, I'm still completely clueless on why this happen.
Anyway, i introduced a specific workaround that reverts the MacOS problematic commit.
Since the workaround should not impact performance on systems that work fine, it has to be manually enabled in the code by uncommenting a line in shaders/config.inc.
Please, search for:
```
	//Workaround for https://github.com/kokoko3k/koko-aio-slang/issues/3
//#define MAC_VIGNETTE_CURVATURE_WORKAROUND 1.0
```
And turn it into:
```
	//Workaround for https://github.com/kokoko3k/koko-aio-slang/issues/3
#define MAC_VIGNETTE_CURVATURE_WORKAROUND 1.0
```

Let me know if this is enough to make it behave like before on MacOS

**Comment by estefan3112** [comment]
Ok, this now comes as a real surprise: 
Same effect under Windows 11 with today's Github code (both FinalBurn Neo and MAME2003, RetroArch Nightly of 11 January 2023), exactly the same behavior:
![1942-230213-184256](https://user-images.githubusercontent.com/24915559/218533614-3315d29b-eef7-43fb-a615-408e2cae6309.png)
Also stock slangp with background:
![1942-230213-185857](https://user-images.githubusercontent.com/24915559/218536172-fe278fab-c7cc-4bed-b92d-74ba4c8ae433.png)

The workaround resolves the problem here under Windows 11. As in MacOS, only vertical games are affected. Now heading back to MacOS. I need to re-test iOS, i.e. whether I applied the newest shader code correctly.
Cheers!

**Comment by kokoko3k** [comment]
Does windows and macos use the same output resolution?
Does things change if running in a smaller window or at 1920x1080 in fullscreen?

**Comment by kokoko3k** [comment]
Ooh, half/good news.
I reproduced under Linux, with amd drivers, but i don't develop on this machine.
I'll try nvidia drivers asap.

**Comment by estefan3112** [comment]
> Does windows and macos use the same output resolution? 
No. Windows 11 has a 2560 x 1440 — QHD (Quad HD) / 2K 1440p (144Hz gaming monitor)
MacOS runs 3840 x 2160 — UHD (Ultra HD) / 4K 2160p (4K dell monitor)

> Does things change if running in a smaller window or at 1920x1080 in fullscreen? 
Windowed mode and fullscreen mode results in identical results. I would still have to check 1080p, though.

> Also, what hapoens if you set the corner sharpness to a very low value? 
Corner sharpness down to 15 results in a nearly black screen, you hardly see the video. On the screenshot, you actually see nothing, but in fact there is some nearly black movement on the screen.
<img width="1440" alt="Bildschirm­foto 2023-02-13 um 19 25 56" src="https://user-images.githubusercontent.com/24915559/218543073-43ce53b2-d223-4732-ad66-539a4f0fe1a4.png">

> I think the corner is the only setting that could actually produce the issue... 

> And last question: are you testing without any modification to the cores stock configuration?
MAME2003 is without any Core Setting changes. 
FinalBurn Neo: Force 60hz ON and Allow Patched Romsets OFF, but no change in standard settings, just tried.

Cheers!

**Comment by kokoko3k** [comment]
It turned out intel drivers were the only ones where it worked fine.
It's ok, i've an nvidia card i can test on easilly, and i hope to fix this mess in a couple of days.
Thank you for reporting!

**Comment by estefan3112** [comment]
> Ooh, half/good news. I reproduced under Linux, with amd drivers, but i don't develop on this machine. I'll try nvidia drivers asap.

My Windows 11 PC (actually, that of my son) runs a GeForce RTX 2070 Super and produces those results.

**Comment by estefan3112** [comment]
And eventually reconfirming: RetroArch iOS on my iPad is not affected, the bezels just work without the static workaround (same codebase as tested under MacOS). So strange.

**Comment by kokoko3k** [comment]
I'm still not 100% sure to have understood why that happen, but i managed to find a way to make it stop, at least on intel and nvidia.
Can you test please?

**Comment by estefan3112** [comment]
Hi, I could only test under MacOS today, and the regular shader presets work!!!

However, there is now a problem with the backdrop configuration - backdrops are not shown, I checked against yesterday's codebase, where the backdrops still work. Foreground artwork works.

<img width="1440" alt="Bildschirm­foto 2023-02-14 um 22 46 45" src="https://user-images.githubusercontent.com/24915559/218871413-64ebe227-e56f-45b4-8d74-4082e15e7b9e.png">

**Comment by estefan3112** [comment]
One second, I think I simply forgot the static setting for backdrops, sorry! Will check again

**Comment by kokoko3k** [comment]
It is working fine here.

**Comment by estefan3112** [comment]
I checked again with today's codebase, and it all works properly on MacOS! No time for Windows tests, but no worries, I guess. So you will probably delete this Mac workaround from config.inc and close here, right?

**Comment by kokoko3k** [comment]
Yes ofc, i think I Already did that ;)
