### ISSUE TITLE
rotate TUBE

### ISSUE THREAD

**Issue by skysix2** [kokoko3k/koko-aio-slang#4]
ciao!

probabilmente non è il posto giusto dove farti delle richieste , mi scuso in anticipo
è possibile aggiungere la funzionalità di "rotate TUBE" come quella presente in "HSM mega bezel" ?

grazie per il tuo lavoro !

**Comment by kokoko3k** [comment]
Sí certo, anzi, dovrebbe essere questo il canale preferenziale.
Mi spieghi a cosa serve e cosa fa?

**Comment by skysix2** [comment]
eccomi , scusa il ritardo

ho costruito un arcade cabinet con lo schermo che può ruotare di 90 gradi, questo perche il TATE mode dei giochi verticali nel mame fa si che lo schermo di gioco si riduca di un bel po' (se il monitor è normalmente in orrizontale)
![IMG_20230729_171853-ridotta](https://github.com/kokoko3k/koko-aio-slang/assets/105243640/bdd80f52-56e1-46a9-9d77-8f892b2f99e9)
mentre se è in posizione verticale , praticamente ha la stessa dimensione dei giochi orrizzontali:
![IMG_20230729_171946-ridotta](https://github.com/kokoko3k/koko-aio-slang/assets/105243640/50b713ce-a74e-42b8-b1e4-0f84f3765d18)
io uso batocera e lr-mame per poter usare gli shader, il problema della rotazione dell'immagine del CORE era abilmente risolto automaticamente dallo shader "mega bezel" senza ulteriori settaggi ne in batocera ne in retroarch, mi è bastato salvare il preset di batocera con un altro nome e aggiungere il settaggio del "rotate CRT" a 90 o 270 al momento mi sfugge..
ad ogni modo per la scheda video sul quale gira tutto devo usare i preset LITE di megabezel , poi ho scoperto il tuo shader che è altrettanto fantastico ed usa al massimo il 60% della GPU, perfetto per me , ma manca la funzionalità della rotazione CRT come descritto sopra (non so se ruoti anche la cornice riflettente) 

grazie ancora !!

**Comment by kokoko3k** [comment]
Ok, chiaro il problema, che invidia altroché :)

Comunque, prima di pe sare di aggiungere features, che anche se innocenti portano via cicli gpu, vorrei essere sicuro che non esistano altre vie.

Per esempio, con retroarch credo esista la possibilitá di ruotare a priori lo schermo tramite le opzioni del core del mame e poi di salvare queste impostazioni per il gioco.
leggo in giro che batocera poi permette di accedere al menu di retroarch, per cui mi chiedo se tu abbia giá vagliato tale possibilitá...

**Comment by skysix2** [comment]
apprezzo l'ottimizzazione !!

in realtà si , il problema è che succede questo: 

shader mega-bezel


![IMG_20230729_193016-ridotta](https://github.com/kokoko3k/koko-aio-slang/assets/105243640/df62e80b-c6af-46cf-84f2-e23651437e0b)

shader koko-aio

![IMG_20230729_194429-ridotta](https://github.com/kokoko3k/koko-aio-slang/assets/105243640/a16aa854-ebea-42ba-9f49-24abb7588907)


forse si può risolvere a livello di come lo shader interpreta le dimensioni del monitor, per capire che è stato ruotato?
e poi nelle istruzioni di installazione di mega-bezel viene specificato di disabilitare la possibilità dei CORE di ruotare
forse perchè si arrangia in automatico lo shader quando serve ??

ovviamente il mio non è un caso preso in considerazione, ma se riuscissi a risolverlo con il CORE ruotato da retroarch sarebbe altrettanto perfetto !!

**Comment by kokoko3k** [comment]
Ok questo accade perché stai usando un core che ruota l'immagine nello stadio finale e koko aio riesce a capirlo e si comporta di conseguenza.
Nella prossima versione stabile di RA i core potranno comunicare la rotazione del gioco allo shader che dovrá decidere come comportarsi, presumibilmente annullarla nei casi normali, ma nel tuo caso semplicemente ignorarla.

Comunque ok, nell'attesa della prossima versione di retroarch nei prox giorni vedró di implementarla nella versione di sviluppo di koko aio e poi magari la modifico.

**Comment by skysix2** [comment]
eccomi,
ho provato i tuoi suggerimenti , ma non trovo il TATE mode in lr-mame (in versione 0.251 su bato 37) 
batocera gira su un ryzen 2400G e 8GB ram , uso quindi lr-mame e non lr-mame2003plus e anche le rom sono aggiornate
e non partono sul 2003plus .
effettivamente lr-mame è meno integrato in RA rispetto a 2003plus e probabilmente il TATE mode manca proprio
così lo shader risolveva tutti i problemi, e non devo cambiarlo ogni vota , lo impostavo dal menu di batocera per singolo gioco
quindi l'impostazione era una tantum e poi tutto era automatico

**Comment by kokoko3k** [comment]
Se esistesse il plus per batocera, con il tate mode non dovresti nemmeno impostarlo gioco per gioco.

é una cosa possibile?

**Comment by kokoko3k** [comment]
qui dice che tate mode esiste in lr mame  e fa proprio ció che ti serve
https://retropie.org.uk/docs/lr-mame2003/

**Comment by skysix2** [comment]
wow grazie per le risposte super celeri...

la documentazione di retropie fa riferimento al core lr-mame2003/078 o lr-mame2003plus/078plus non al lr-mame in versione corrente che si puo usare sui sistemi PC e non sulle SBC tipo raspberry perche troppo pesante per questi, e puo usare il romset completo del mame ufficiale

**Comment by skysix2** [comment]
adesso i provo dal menu interno (TAB) di lr-mame...

**Comment by skysix2** [comment]
ok risolto !!
ruotare il monitor dal menu interno del mame risolve il problema mantenendo bene le proporzioni !!!
a questo punto ritiro la richiesta !! grazie comunque per il tuo tempo !!

ps. ho notato che il tuo shader non rispetta lo zoom a pixel perfect come invece fa mega-bezel , ma semplicemente riempie lo schermo disponibile , e un comportamento voluto? oppure ho sminchiato qualcosa io a forza di prove ?

grazie ancora!

**Comment by kokoko3k** [comment]
per il pixel perfect,
in geometry overrides devi abilitare l'integer scaling, occhio che alcune opzioni lo scavalcano (sono segnalate comunque).

dai un occhio a docs-ng.md

**Comment by skysix2** [comment]
> e sei sicuro non ci sia il tate mode? é moolto strano e renderebbe tutto automatico.

in lr-mame current si, non cè , ma come detto si risolve dal menu del mame

> 
> per il pixel perfect, nelle opzioni dello shader, in geometry overrides devi abilitare l'integer scaling, occhio che alcune opzioni lo scavalcano,(alcune sono segnalate comunque).
> 
> dai un occhio a docs-ng.md

ok grazie !!
