### ISSUE TITLE
Suggestion for flat CRT and handhelds

### ISSUE THREAD

**Issue by gravelfreeman** [kokoko3k/koko-aio-slang#7]
Hi, first and foremost I want to thank you for all of the incredible work you've done. I tried so many shaders and overlays in the last decade and yours are much better than everything I ever seen.

For more recent systems I would love to see your shaders with a flat HD Sony CRT/or whatever it was called. I like to use this overlay for PS2 and higher but it's not compatible with your shaders unfortunately. It's made by Exodus and can source can be downloaded [here](https://forums.libretro.com/t/exodus-crt-tvs-overlays-collection-with-day-and-night-support/9192).

![crt-flat](https://github.com/kokoko3k/koko-aio-slang/assets/44218371/4fa7c4b9-267d-4672-9f90-0f58e19f0a84)

I would love to see these versions of the handhelds to match your current CRT design. The current ones seems a bit off being pictures of the real hardware. I think those renderings are closer to your project and fit with the current CRT. Also  the screen field is  bigger for all of them which makes it a plus playing on the TV.

Let me know what you think!

![Nintendo-Gameboy](https://github.com/kokoko3k/koko-aio-slang/assets/44218371/53822ce2-92e4-42bd-ab53-2d6751556afd)

![Nintendo-GBC](https://github.com/kokoko3k/koko-aio-slang/assets/44218371/59939889-71a9-499a-92a3-2e157ee5c425)

![Nintendo-GBA](https://github.com/kokoko3k/koko-aio-slang/assets/44218371/1d5e23ca-8ee9-4c83-9272-30986c7654fa)

![Nintendo-Virtualboy](https://github.com/kokoko3k/koko-aio-slang/assets/44218371/c590b4ac-d467-4dda-ba37-b4bf6fbcfd24)

![Sega-GameGear](https://github.com/kokoko3k/koko-aio-slang/assets/44218371/2b1f7a4d-5f7c-42c3-968a-06229ac70563)

![Atari-Lynx](https://github.com/kokoko3k/koko-aio-slang/assets/44218371/f3e7d905-b4c6-4ab1-bc79-0b369fd2d4f9)

![Neogeo-Pocket](https://github.com/kokoko3k/koko-aio-slang/assets/44218371/f7f80c39-eb46-48be-9b4f-650c9b10c4fd)

![wswan](https://github.com/kokoko3k/koko-aio-slang/assets/44218371/14836fc9-1d15-47af-b58c-e137ed08033a)

Also a generic Vectrex one which someone could just add the game overlay on top of your shader afterwards. If you think that wouldn't work, I can provide the same overlay for all of the Vectrex games.

![GCE-Vectrex](https://github.com/kokoko3k/koko-aio-slang/assets/44218371/bcb8f593-8f69-4ba3-b87e-084f38339715)

I can't find the source for the handhelds but if it's interesting you, I can search later to find it so you can credit the original author.

Thank you!

**Comment by kokoko3k** [comment]
Hi there!

I'm afraid i don't quite understood what the question is, those bezels look ok to me and should work without problems with koko-aio, maybe a bit of work is needed to delete the mask on some of the handelds with a graphic program, but i don't see blocking issues.

Btw, there is a repo containing a lot of bezel presets here:<br>
https://github.com/kokoko3k/koko-aio-slang-presets-and-overlays

Maybe you want to look at them to have an idea on how they are done and submit you presets there?

**Comment by kokoko3k** [comment]
Closing because of no reply.
Feel free to reopen if still interested.
