### ISSUE TITLE
Batocera V39 and Koko-AIO 19: Amiga decoration is wrong (Commodore64)

### ISSUE THREAD

**Issue by giancarloerra** [kokoko3k/koko-aio-slang#8]
Just discovered this set of shaders and it's very impressive!

Using it in Batocera, when emulating Amiga (default Retroarch PUAE core) the bezel is of Commodore 64 ,not Amiga.

Any suggestion how I can fix it?

**Comment by kokoko3k** [comment]
> Just discovered this set of shaders and it's very impressive!
> 
> Using it in Batocera, when emulating Amiga (default Retroarch PUAE core) the bezel is of Commodore 64 ,not Amiga.
> 
> Any suggestion how I can fix it?

You sure it is from c64? Isn't it just a monitor?

Btw, I've no control over Batocera's package/set, so you should ask them for help or to file a bug report.

I know for sure they ship a vanilla koko-aio package which comes with a default 1084S bezel which I remember was sold by Commodore in Amiga era.

**Comment by giancarloerra** [comment]
> > Just discovered this set of shaders and it's very impressive!
> > Using it in Batocera, when emulating Amiga (default Retroarch PUAE core) the bezel is of Commodore 64 ,not Amiga.
> > Any suggestion how I can fix it?
> 
> You sure it is from c64? Isn't it just a monitor?
> 
> Btw, I've no control over Batocera's package/set, so you should ask them for help or to file a bug report.
> 
> I know for sure they ship a vanilla koko-aio package which comes with a default 1084S bezel which I remember was sold by Commodore in Amiga era.

It's not just a monitor, it's the C64 keyboard (the same that appears in C64 emulation). Without koko-aio Amiga core is loaded with Amiga keyboard, using koko-aio as a shader is c64 instead.

I thought they were simply installing a default koko-aio package/set, if you say it's something they re-package custom for Batocera, then I'll ask them.

Can you point me to some koko-aio doc section that can help me understand where is the configuration for a specific core defined within koko-aio? So I can maybe try fixing it myself. Looking at koko-aio screenshots, I see there's a blank/room ambient/immersive which looks great, but I don't know how to set that up within Batocera menus (but if I understand how to edit it manually directly in the config files then I can do it myself).

Thanks for the quick reply!

**Comment by kokoko3k** [comment]
kokoaio itself has no specofic configurations per core.
That's a batocera thing and I don't know how they packaged my shader in detail. I don't use batocera at all.

The room you are referring to is part of the vanilla/unmodified kokoaio package; maybe ypu can install it in batocera and load the ambilight immersive preset, that's all I can help you with; for further specific Batocera support, you should ask them.

They have an active Discord supprt channel:
https://discord.com/channels/357518249883205632/1184376479065329675
